### ISSUE TITLE
Test case for #33

### ISSUE THREAD

**Issue by deep5050** [deep5050/MastJokeMara#37]
Checking if it still commnets back to a bot or not. #33

**Comment by deep5050** [comment]
:tada: It now avoids bot comments :sunglasses: 

> Not closing this issue just for future experiments

**Comment by krazy4code** [comment]
Need to avoid owner's reply too. It should not comments raised by the owner. Also replying back to the owner's comments. Over all it should comment for the first time only to the original issue raiser.

**Comment by deep5050** [comment]
Hi @krazy4code, thanks for raising this issue. I'm labeling this as a  bug too. Please raise an seperate issue by referencing it.
