### ISSUE TITLE
Avoid owner's reply too

### ISSUE THREAD

**Issue by krazy4code** [deep5050/MastJokeMara#38]
Need to avoid owner's reply too. It should not comment back on issues raised by the owner. Also replying back to the owner's further comments. Over all it should comment for the first time only to the original issue raiser.

_Originally posted by @krazy4code in https://github.com/deep5050/MastJokeMara/issues/37#issuecomment-708920044_

**Comment by deep5050** [comment]
okay, labeling and commenting back on an issue also causing the workflow to run. That's a serious issue.

**Comment by deep5050** [comment]
This might solve the issue. 

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#issues
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request
