### ISSUE TITLE
currently user have no access to what will be the greeting message

### ISSUE THREAD

**Issue by mayankmohak** [deep5050/MastJokeMara#43]
**Problem**
Can't apply message according to my choice.

**Request**
I want to use this for a repo but want the message according to me. and think this should be a new version as if it is also a most needed feature.

**Comment by deep5050** [comment]
@mayankmohak i'm already working on this. Soon it will be published. Thanks again (from the human) 😄

**Comment by deep5050** [comment]
@mayankmohak I have added the feature, test it and freely use in your repo. Happy Coding :+1:
