### ISSUE TITLE
message not working for PRs.

### ISSUE THREAD

**Issue by mayankmohak** [deep5050/MastJokeMara#49]
**Describe the bug**
I think there is some bug in the bot message for PR.
View pr #48

**Comment by deep5050** [comment]
https://github.community/t/github-actions-are-severely-limited-on-prs/18179


GitHub doesn't allow access to a fork based pull request from a workflow yet! 
Once they add this support I'll change code accordingly.

**Comment by mayankmohak** [comment]
i am leaving it opened for others to have a reference.

**Comment by mayankmohak** [comment]
can you make a branch of it without pr greet

**Comment by deep5050** [comment]
I'm planning for converting it to a GitHub marketplace app. A github app has read and write permission to a Pull Request. For now just remove the pull request are under workflow yaml file. I'm having a busy schedule so don't know when I will start doing so.

> I'm looking for contributors for this repo and the next app.

**Comment by mayankmohak** [comment]
Ok thanks a lot dear.

**Comment by deep5050** [comment]
Use memes instead of jokes on new issues
[memes-on-issues](https://github.com/deep5050/memes-on-issues-action)

**Comment by deep5050** [comment]
GitHub has added a few things in the action API. I think it is possible now.

**Comment by deep5050** [comment]
Hi @mayankmohak 
This action now supports commenting on fork-based pull requets.
check readme and update your workflow accordingly. Inform other project owners too. 

### Thanks
